### ISSUE TITLE
Need Project name over the Task name

### ISSUE THREAD

**Issue by michaellu51** [Raathigesh/Lazymine#82]
I have tasks with the same name in different projects , so only way to check is by hovering over the colored icon to check the project.

**Comment by chathuranga** [comment]
I think this is valid. Here's what I see in my Lazymine
![image](https://cloud.githubusercontent.com/assets/71325/8666538/7f8a249c-2a10-11e5-934a-b6e30a061256.png)
I'd suggest below approach to address this.
1. Introduce a configuration entry, a regular expression to extract the Charactor to represent the project
2. Then regular expression could be customized to match our needs
ex. if the Project Name format is [Zone24x7] Architect Circle [ARCIR] - Letter should be "A" instead of being "Z"

@michaellu51  would the above address your concern? (without putting the full project name laking lot of space)

**Comment by chathuranga** [comment]
Fixed like below, with dc8e23eb10cb816643e411b2315cd5e55bf8ffe4.
![img_13082015_102522](https://cloud.githubusercontent.com/assets/71325/9248076/71525e34-41d6-11e5-8a0a-99ed52ef9ca4.png)
