### ISSUE TITLE
Time entered tasks takes too much time to load. 

### ISSUE THREAD

**Issue by isuru88** [Raathigesh/Lazymine#95]
#### Steps to recreate
- Open Lazymine
- Wait for the loading screen to dissapear
##### Expected Result
- Time entered tasks should be there in the list once the loading is complete
##### Actual Result
- Time entered tasks appear after a few seconds

**Comment by chathuranga** [comment]
Had a look at what's going on. The issue seems to be due to the new data fetch, getTimeEntriesForWeek done at the componentDidMount of the app-Container.
@Raathigesh,I think we should be calling this method from the data-manager's fetchData adding another call similar to getTaskCollection and getTimeEntryActivities.
That way State.isLoading would be handled from a single location, where it's done from two places now making the pre-loader go away right after returning short call of getting the time entries for the week.

**Comment by chathuranga** [comment]
Someone to check it and close :)

**Comment by Raathigesh** [comment]
Works fine!
